title: "FutureWLHS"
description: "Misinformation for the masses"
baseurl: "" # keep empty for USERNAME.github.io root
url: "https://futurewlhs.com"
theme: null
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
future: true
timezone: America/Los_Angeles
